modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "weatherwatch"
version = "${version}"
displayName = "WeatherWatch"
authors = "Consular"
description = '''

'''
#logoFile = ""

[[dependencies.weatherwatch]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.weatherwatch]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11]"
ordering = "NONE"
side = "BOTH"

[[dependencies.weatherwatch]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "weatherwatch.mixins.json"
